name: Build on Commit

on:
  push:
    branches: [dev]
    tags-ignore: ["*"]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MDGJX_ROOT: /home/runner/work/MDGJX/MDGJX
      OVERRIDED_VERSION: v1.9.9-beta
      DOCKERUSER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERTOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21

      - name: Run build script
        run: |
          npm i -g typescript
          cd ./modules/web2
          cd ../../
          cd ./pipeline
          chmod +x ./build-all.sh
          ./build-all.sh
